language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - pypy

matrix:
  allow_failures:
    - python: 3.2  # Not a new enough 3.2 for blessings
    - python: pypy  # PyPy doesn't have _curses.

script:
  - pip install -q --use-mirrors nose
  - python setup.py install
  - nosetests -w /tmp blessings.tests
