#!/bin/bash

# this wrapper tries to chose a preferred interpreter

for i in pypy python3 python2;
do
  if type $i > /dev/null;
  then
    args="${*:1}"
    $i yana.py ${args[@]}
    exit $?
  fi
done
